### ISSUE TITLE
Bug: Following some users after signing up

### ISSUE THREAD

**Issue by petya-** [DevOps2021-gb/devops2021#44]
## Expected Behavior
When I sign up, I should not follow anyone

## Current Behavior
When I sign up with a new user (my account: petya2), I am already following some users

## Steps to Reproduce
1. Create a new account
2. Visit few profiles from the public timeline

## Context (Environment)
Tested on  http://144.126.244.138:4567

## Detailed Description
My freshly created user: http://144.126.244.138:4567/petya2
The users I was automatically following after signing up: 
- http://144.126.244.138:4567/sikr
- http://144.126.244.138:4567/ask (Once i manually followed, unfollowed this user, only then he showed up on my personal timeline)
- http://144.126.244.138:4567/nime

**Comment by psiphph** [comment]
We are not able to reproduce this.

**Comment by petyaBuchkovaTL** [comment]
The issue still persists, create a fresh account and go through the list of users on the public timeline, there are some users that are randomly followed. Or at least the front-end is displaying the message that we are following the user. 

My example user that I just created and the message that I see when I go to the timeline of this user: 

<img width="887" alt="Screenshot 2021-03-08 at 08 09 47" src="https://user-images.githubusercontent.com/66465348/110286712-a8227180-7fe5-11eb-932f-2ad62c96ea92.png">

**Comment by petya-** [comment]
The issue still persists for us, however. To reproduce it: create a fresh account and go through the list of users on the public timeline, there are some users that are randomly followed. Or at least the front-end is displaying the message that we are following the user. 

The test user that I just created and the message that I see when I go to the timeline of this user: 

<img width="887" alt="Screenshot 2021-03-08 at 08 09 47" src="https://user-images.githubusercontent.com/66465348/110286712-a8227180-7fe5-11eb-932f-2ad62c96ea92.png">
